#pragma once

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_TIME_TO_MAX 40
#define MOUSEKEY_DELAY 100
#define MOUSEKEY_WHEEL_DELAY 100
#define MOUSEKEY_WHEEL_INTERVAL 50
#define MOUSEKEY_WHEEL_TIME_TO_MAX 100

#define IGNORE_MOD_TAP_INTERRUPT_PER_KEY
#define NO_AUTO_SHIFT_ALPHA
#define TAPPING_FORCE_HOLD_PER_KEY
